version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  app_1:
    image: nginx
    ports:
      - 8001:80
    volumes:
      - ./app_1:/usr/share/nginx/html
  app_2:
    image: nginx
    ports:
      - 8002:80
    volumes:
      - ./app_2:/usr/share/nginx/html